version: '3.8'

services:
  watcher-service:
    build: .
    container_name: idis_watcher
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=sk-YOUR_API_KEY_HERE
      - LOGGING_LEVEL=INFO
    command: >
      python3 watcher_service.py
      --watch-folder /app/data/scanner_output
      --inbox-folder /app/data/idis_inbox
      --holding-folder /app/data/idis_holding
      --archive-folder /app/data/idis_archive
      --cover-sheets-folder /app/data/idis_coversheets
      --db-path /app/data/idis_db_storage/idis.db
      --openai

  ui-service:
    build: .
    container_name: idis_ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: >
      streamlit run app.py
      --server.port 8501
      --server.address 0.0.0.0
      --
      --database-path /app/data/idis_db_storage/idis.db
      --archive-path /app/data/idis_archive

volumes:
  data: