version: '3.8'

services:
  idis:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./watch_folder:/app/watch_folder
      - ./holding_folder:/app/holding_folder
      - ./archive:/app/archive_folder
      - ./cover_sheets:/app/cover_sheets
      - ./database:/app/db
    restart: unless-stopped
    command: [
      "python3", "watcher_service.py",
      "--watch-folder", "/app/watch_folder",
      "--holding-folder", "/app/holding_folder", 
      "--archive-folder", "/app/archive_folder",
      "--cover-sheets-folder", "/app/cover_sheets",
      "--db-path", "/app/db/idis.db",
      "--openai"
    ]