version: '3.8'
services:
  idis_watcher:
    build: .
    container_name: idis_watcher
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  idis_ui:
    build: .
    container_name: idis_ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    command: >
      /usr/local/bin/streamlit run quanta_ui/app.py
      --server.port 8501
      --server.address 0.0.0.0