[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.25.5",
    "pytesseract>=0.3.13",
    "python-docx>=1.1.2",
]
